POST http://localhost:8080/engine-rest/process-definition/key/process_key_goes_here/submit-form
Content-Type: application/json

{
  "variables": {
    "username": {"value":"sitakant","type":"String"},
    "username2":{"value":"12345","type":"String"},
    "dept":{"value":"123","type":"String"}
  }
}

###
## get the camunda deployed process
GET http://localhost:8080/engine-rest/process-definition/
Accept: application/json

### start the process with key

